Second commit HW3
IaroslavPetrov/HW3 pull request #1
Opened 2022-01-27 20:00 UTC by IaroslavPetrov

2022-01-27 20:26 UTC, rmuhamedgaliev requested changes
Давай немного над форматированием поработаем. "Стройный" код легче читать и проще поддерживать что бы в короткие сроки исправлять баги. В Idea есть автоматический форматер. Давай отформатируем код в этом PR и в будущем перед коммитом будем использовать этот механизм - https://blog.jetbrains.com/idea/2020/06/code-formatting/

2022-01-27 20:26 UTC, rmuhamedgaliev commented on src/com/company/Main.java
> +	byte bananas = 5;
Очень здорово, что ты постарался осмысленно назвать переменные 👍

2022-01-28 12:21 UTC, IaroslavPetrov commented
> Давай немного над форматированием поработаем. "Стройный" код легче читать и проще поддерживать что бы в короткие сроки исправлять баги. В Idea есть автоматический форматер. Давай отформатируем код в этом PR и в будущем перед коммитом будем использовать этот механизм - https://blog.jetbrains.com/idea/2020/06/code-formatting/

2022-01-28 12:21 UTC, closed without merging

2022-01-28 18:04 UTC, rmuhamedgaliev reviewed
Принято ✅